// Obzervify prototype — per-company dataset
// Each company is a distinct narrative: sources, signals, epics, scores, and a recommended epic.

window.COMPANIES = {
  stripe: {
    name: 'Stripe',
    kind: 'Fintech',
    note: 'payments infrastructure',
    mark: { bg: '#635BFF', fg: '#fff', char: 'S' },
    sources: [
      { n: 'X / Twitter',     k: 14820 },
      { n: 'Reddit',          k: 3940  },
      { n: 'Zendesk',         k: 8210  },
      { n: 'Intercom',        k: 2104  },
      { n: 'App Store',       k: 612   },
      { n: 'Slack (internal)',k: 4812  },
      { n: 'GitHub Issues',   k: 1420  },
      { n: 'Jira (dev logs)', k: 2205  },
    ],
    stream: [
      { src: 'X',        s: 'neg', t: 'payment_intent fails silently after 3DS redirect on safari 18' },
      { src: 'ZENDESK',  s: 'neg', t: '#8812 · merchant unable to disable a single radar rule' },
      { src: 'REDDIT',   s: 'neu', t: 'r/stripe · "Dashboard chart broken on Safari"' },
      { src: 'SLACK',    s: 'neg', t: '#support-escalations · mexico issuer decline rate up 4x' },
      { src: 'APPSTORE', s: 'neg', t: '★★☆☆☆ "great onboarding, then it all falls apart"' },
      { src: 'X',        s: 'neg', t: 'why does Stripe Atlas take 14 days now' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_9021 · refund flow breaks in mobile Safari' },
      { src: 'GITHUB',   s: 'neu', t: 'issue #4412 · idempotency key reused → 409' },
      { src: 'JIRA',     s: 'neg', t: 'PAY-1187 · fraud false-positive review queue spiking' },
      { src: 'ZENDESK',  s: 'neg', t: '#8844 · 3DS challenge loops on Chromium mobile' },
      { src: 'X',        s: 'pos', t: 'Stripe support just saved our launch day 🙏' },
      { src: 'REDDIT',   s: 'neg', t: 'r/ecommerce · "Radar flagged 12% of valid orders last week"' },
      { src: 'SLACK',    s: 'neg', t: '#eng-fraud · false-positives trending up since v3 model' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_9137 · customer can\'t re-run failed charge' },
      { src: 'X',        s: 'neg', t: 'auth rate dropped 2 points overnight — anyone else?' },
    ],
    clusters: [
      { title: '3DS auth failures on Safari', size: 2140, score: 93.2, top: true },
      { title: 'Radar false-positive surge',   size: 1680, score: 87.4 },
      { title: 'Mexico issuer decline rate',   size: 940,  score: 71.0 },
      { title: 'Atlas onboarding latency',     size: 610,  score: 62.3 },
      { title: 'Refund flow mobile safari',    size: 520,  score: 58.1 },
      { title: 'Dashboard Safari rendering',   size: 312,  score: 41.6 },
      { title: 'Idempotency 409 edge cases',   size: 188,  score: 38.9 },
    ],
    top: {
      title: 'Resolve payment_intent 3DS failures on Safari',
      why: 'Stripe\'s clearest live insight is a spike in 3DS authorization failures on Safari 18, reinforced by cross-channel evidence: 2,140 signals from X, Zendesk and Reddit, correlated to a 2-point auth-rate dip in production.',
      rec: 'Prioritize payment success and onboarding trust before expanding account surfaces.',
      rice: { R: 92, I: 88, C: 96, E: 18 },
      score: 93.2,
      verdict: 'Ship-critical — revenue-impacting in week one.',
      accept: [
        'Handle apple-pay 3DS redirect race on Safari 18',
        'Fall back to native challenge when top-frame blocked',
        'Emit payment_intent.auth_failed with frame_blocked reason',
        'Dashboard surfaces affected merchants within 30 min',
      ],
      evidence: [
        { q: 'My auth rate just dropped 2 points overnight. Only Safari users.', src: 'X · merchant' },
        { q: '#8812 — customer can complete 3DS but intent never confirms.', src: 'Zendesk · P1' },
        { q: 'Radar flagged 12% of valid orders after the v3 rollout.', src: 'r/ecommerce' },
      ],
      jira: { id: 'PAY-2041', type: 'Epic', proj: 'Payments', pts: 21 },
      conf: { space: 'PAY', title: 'PRD · Safari 3DS auth resilience' },
    },
    counts: { signals: 38163, pct: { pos: 18, neu: 34, neg: 48 }, epics: 7, runtimeSec: 38 },
  },

  shopify: {
    name: 'Shopify',
    kind: 'Commerce',
    note: 'merchant platform',
    mark: { bg: '#5A8F29', fg: '#fff', char: 'S' },
    sources: [
      { n: 'X / Twitter',     k: 11200 },
      { n: 'Reddit r/shopify',k: 6210  },
      { n: 'Zendesk',         k: 9820  },
      { n: 'App Store review',k: 1812  },
      { n: 'Play Store',      k: 1420  },
      { n: 'Slack (internal)',k: 3990  },
      { n: 'GitHub Issues',   k: 712   },
      { n: 'Jira (dev logs)', k: 1806  },
    ],
    stream: [
      { src: 'REDDIT',   s: 'neg', t: 'r/shopify · "Checkout extension crashes on mobile during BFCM rehearsal"' },
      { src: 'X',        s: 'neg', t: 'Shopify Magic is generating duplicate product descriptions' },
      { src: 'ZENDESK',  s: 'neg', t: '#7721 · Shop Pay not applying discount code on draft orders' },
      { src: 'APPSTORE', s: 'neg', t: '★☆☆☆☆ "Shop app push notifications are spammy again"' },
      { src: 'SLACK',    s: 'neg', t: '#partner-ecosystem · theme dev cannot preview on 2.0 templates' },
      { src: 'X',        s: 'pos', t: 'Shopify Markets saved me 14 hours this week' },
      { src: 'ZENDESK',  s: 'neg', t: '#7740 · bulk editor times out on catalogs > 50k SKUs' },
      { src: 'REDDIT',   s: 'neu', t: 'r/entrepreneur · "Is Shopify Audiences worth it?"' },
      { src: 'X',        s: 'neg', t: 'why does Shop Pay fail on iPhone mini viewport' },
      { src: 'JIRA',     s: 'neg', t: 'CHECK-812 · discount stacking edge case, 400ms regression' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_2201 · merchant lost $14k on BFCM — checkout hung' },
      { src: 'SLACK',    s: 'neg', t: '#incident · checkout latency p95 creeping up' },
      { src: 'GITHUB',   s: 'neu', t: 'shopify/cli#4488 · dev preview broken on M-series' },
      { src: 'PLAY',     s: 'neg', t: '★★☆☆☆ "POS Go barcode scanner unreliable"' },
      { src: 'X',        s: 'neg', t: '"Shop Pay Installments" UX is deeply confusing at checkout' },
    ],
    clusters: [
      { title: 'Checkout p95 latency regression', size: 1920, score: 91.8, top: true },
      { title: 'Bulk editor timeout on large catalogs', size: 1430, score: 82.7 },
      { title: 'Shop Pay discount-code edge cases', size: 1120, score: 77.4 },
      { title: 'Shopify Magic duplicate outputs',  size: 860,  score: 68.0 },
      { title: 'Theme dev preview broken',         size: 540,  score: 54.1 },
      { title: 'Shop app notification fatigue',    size: 480,  score: 47.8 },
      { title: 'POS Go barcode reliability',       size: 260,  score: 36.2 },
    ],
    top: {
      title: 'Cut checkout p95 latency ahead of Q4 peak',
      why: 'Shopify\'s loudest signal is a creeping p95 checkout latency, corroborated by merchants losing sales on BFCM rehearsal traffic and internal Jira showing a 400ms discount-stacking regression.',
      rec: 'Lock checkout performance before launching any new checkout extension surface area.',
      rice: { R: 96, I: 92, C: 91, E: 24 },
      score: 91.8,
      verdict: 'Revenue-preserving — ship before BFCM freeze.',
      accept: [
        'p95 checkout < 1.2s on all top-50 merchant themes',
        'Revert or gate discount-stacking regression in CHECK-812',
        'Synthetic checkout canary wired to merchant Slack',
        'Merchant-facing status page surfaces regional latency',
      ],
      evidence: [
        { q: 'Merchant lost $14k on BFCM — checkout just hung for 4 minutes.', src: 'Intercom · tier-1' },
        { q: 'Checkout extension crashes on mobile during our BFCM rehearsal.', src: 'r/shopify' },
        { q: 'CHECK-812 — 400ms regression on discount-stacking path.', src: 'Jira · internal' },
      ],
      jira: { id: 'CHECK-2210', type: 'Epic', proj: 'Checkout', pts: 34 },
      conf: { space: 'CHECK', title: 'PRD · Checkout p95 resilience, Q4' },
    },
    counts: { signals: 36970, pct: { pos: 22, neu: 38, neg: 40 }, epics: 7, runtimeSec: 41 },
  },

  notion: {
    name: 'Notion',
    kind: 'Productivity',
    note: 'workspace & docs',
    mark: { bg: '#111', fg: '#fff', char: 'N' },
    sources: [
      { n: 'X / Twitter',     k: 8420 },
      { n: 'Reddit r/Notion', k: 5240 },
      { n: 'Intercom',        k: 4610 },
      { n: 'App Store',       k: 2120 },
      { n: 'Play Store',      k: 1140 },
      { n: 'Slack (internal)',k: 2430 },
      { n: 'GitHub feedback', k: 410  },
      { n: 'Linear',          k: 1104 },
    ],
    stream: [
      { src: 'X',        s: 'neg', t: 'Notion AI keeps hallucinating quarters in my finance doc' },
      { src: 'REDDIT',   s: 'neg', t: 'r/Notion · "Sync conflicts destroyed my 6-month wiki"' },
      { src: 'APPSTORE', s: 'neg', t: '★★☆☆☆ "offline mode still doesn\'t work in 2026"' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_3210 · team lost nested DB relations overnight' },
      { src: 'X',        s: 'pos', t: 'Notion Calendar is the first calendar app I actually like' },
      { src: 'SLACK',    s: 'neg', t: '#eng-sync · merge conflicts on nested pages up 3x' },
      { src: 'REDDIT',   s: 'neu', t: 'r/productivity · "Notion vs Obsidian 2026 edition"' },
      { src: 'LINEAR',   s: 'neg', t: 'SYNC-4402 · page content flickers to stale version briefly' },
      { src: 'PLAY',     s: 'neg', t: '★★☆☆☆ "Android app crashes on large databases"' },
      { src: 'X',        s: 'neg', t: 'Notion AI charged me for a duplicate run — support?' },
      { src: 'ZENDESK',  s: 'neg', t: '#5512 · admin can\'t see audit log for AI usage' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_3255 · enterprise asks for AI output attribution' },
      { src: 'REDDIT',   s: 'neg', t: 'r/Notion · "Whole page rolled back 2 days"' },
      { src: 'SLACK',    s: 'neg', t: '#trust · compliance wants a data-residency page' },
      { src: 'X',        s: 'neg', t: 'how do I stop Notion AI from writing in the wrong voice' },
    ],
    clusters: [
      { title: 'Sync conflict & silent data loss', size: 1820, score: 94.1, top: true },
      { title: 'Notion AI hallucinations & attribution', size: 1340, score: 84.0 },
      { title: 'Offline mode gaps',                 size: 910,  score: 73.2 },
      { title: 'Enterprise audit / AI billing',     size: 640,  score: 66.5 },
      { title: 'Android large-DB crashes',          size: 480,  score: 54.7 },
      { title: 'Notion Calendar polish',            size: 340,  score: 42.0 },
      { title: 'AI voice / style drift',            size: 210,  score: 34.4 },
    ],
    top: {
      title: 'End silent sync conflicts on nested pages',
      why: 'Notion\'s most intense signal is trust loss from sync conflicts that silently overwrite nested content. Two weeks of Reddit, Intercom, and Linear all point at the same root cause.',
      rec: 'Invest in conflict-free durability before shipping any new collaborative surface.',
      rice: { R: 88, I: 96, C: 94, E: 32 },
      score: 94.1,
      verdict: 'Trust-critical — every lost page is a churn event.',
      accept: [
        'CRDT fallback for nested DB relations on reconnect',
        'Conflict log surfaced per-page with restore action',
        'Sync-health indicator in page header',
        'p99 merge completes < 200ms after reconnect',
      ],
      evidence: [
        { q: 'Whole page rolled back 2 days — and no one on support can explain why.', src: 'r/Notion' },
        { q: 'Team lost all nested DB relations overnight after a sync.', src: 'Intercom · biz' },
        { q: 'SYNC-4402 — content flickers to a stale version on reconnect.', src: 'Linear · internal' },
      ],
      jira: { id: 'SYNC-4501', type: 'Epic', proj: 'Sync', pts: 55 },
      conf: { space: 'SYNC', title: 'PRD · Conflict-free nested durability' },
    },
    counts: { signals: 25474, pct: { pos: 28, neu: 34, neg: 38 }, epics: 7, runtimeSec: 44 },
  },

  airbnb: {
    name: 'Airbnb',
    kind: 'Marketplace',
    note: 'travel & hosting',
    mark: { bg: '#FF5A5F', fg: '#fff', char: 'A' },
    sources: [
      { n: 'X / Twitter',     k: 12230 },
      { n: 'Reddit',          k: 8420  },
      { n: 'App Store',       k: 4210  },
      { n: 'Play Store',      k: 2820  },
      { n: 'Zendesk',         k: 7920  },
      { n: 'Slack (internal)',k: 2810  },
      { n: 'LinkedIn',        k: 540   },
      { n: 'Jira',            k: 1120  },
    ],
    stream: [
      { src: 'X',        s: 'neg', t: '"cleaning fee" memes trending again — 6 hours in' },
      { src: 'REDDIT',   s: 'neg', t: 'r/AirBnB · "Host cancelled 36h before check-in, no real refund"' },
      { src: 'APPSTORE', s: 'neg', t: '★☆☆☆☆ "Hidden fees on final screen — bait and switch"' },
      { src: 'ZENDESK',  s: 'neg', t: '#6612 · guest locked out, host unreachable' },
      { src: 'X',        s: 'neg', t: 'why does Airbnb show price WITHOUT fees in feed still' },
      { src: 'SLACK',    s: 'neg', t: '#trust-ops · superhost churn in EU up 2x QoQ' },
      { src: 'REDDIT',   s: 'neg', t: 'r/travel · "Airbnb is more expensive than hotels now"' },
      { src: 'X',        s: 'pos', t: 'Airbnb icons are genuinely charming, good work team' },
      { src: 'INTERCOM', s: 'neg', t: 'conv_4412 · host wants cleaning-fee bundled by default' },
      { src: 'ZENDESK',  s: 'neg', t: '#6640 · payout delayed 11 days, no ETA' },
      { src: 'REDDIT',   s: 'neg', t: 'r/AirbnbHosts · "New pricing tool tanked my occupancy"' },
      { src: 'X',        s: 'neg', t: 'Airbnb guest tried to extort a 5-star review — no recourse' },
      { src: 'APPSTORE', s: 'neg', t: '★★☆☆☆ "search filters forget themselves between tabs"' },
      { src: 'JIRA',     s: 'neg', t: 'TRUST-2240 · refund SLA missed for 8% of cases last week' },
      { src: 'LINKEDIN', s: 'neu', t: 'analyst · "Airbnb fee perception is a structural issue"' },
    ],
    clusters: [
      { title: 'Total-price transparency failures', size: 2310, score: 95.4, top: true },
      { title: 'Host cancellations & refunds',      size: 1820, score: 88.1 },
      { title: 'Superhost churn / pricing tool',    size: 1180, score: 79.2 },
      { title: 'Guest extortion & review abuse',    size: 740,  score: 70.5 },
      { title: 'Payout delays',                     size: 620,  score: 64.0 },
      { title: 'Search filter persistence',         size: 440,  score: 48.3 },
      { title: 'Lockbox / check-in failures',       size: 320,  score: 41.6 },
    ],
    top: {
      title: 'End total-price transparency failures in feed',
      why: 'Airbnb\'s sharpest cross-channel signal is mistrust around total-price display. App Store reviews, viral X posts and analyst commentary all reinforce: the brand damage is structural.',
      rec: 'Make total price the default everywhere before any new growth surface ships.',
      rice: { R: 98, I: 94, C: 92, E: 16 },
      score: 95.4,
      verdict: 'Brand-critical — a headline risk every weekend.',
      accept: [
        'Total-with-fees price is the default in every feed',
        'Per-night price shown only on toggle, not a flag in search',
        'Server-side A/B that proves conversion lift or churn neutral',
        'Fee breakdown expandable in one tap',
      ],
      evidence: [
        { q: 'Hidden fees on the final screen — bait and switch.', src: 'App Store · 1★' },
        { q: 'Airbnb is more expensive than hotels now, and we can\'t even see why.', src: 'r/travel' },
        { q: 'Fee perception is a structural issue for the marketplace.', src: 'LinkedIn · analyst' },
      ],
      jira: { id: 'TRUST-3301', type: 'Epic', proj: 'Trust', pts: 42 },
      conf: { space: 'TRUST', title: 'PRD · Total-price by default' },
    },
    counts: { signals: 40070, pct: { pos: 16, neu: 30, neg: 54 }, epics: 7, runtimeSec: 46 },
  },

  github: {
    name: 'GitHub',
    kind: 'Developer',
    note: 'code collaboration',
    mark: { bg: '#0D1117', fg: '#fff', char: 'G' },
    sources: [
      { n: 'X / Twitter',     k: 6810  },
      { n: 'Reddit r/github', k: 2440  },
      { n: 'Hacker News',     k: 1820  },
      { n: 'Community forum', k: 4120  },
      { n: 'Zendesk',         k: 5210  },
      { n: 'Slack (internal)',k: 3210  },
      { n: 'GitHub issues',   k: 8820  },
      { n: 'Jira / Azure DO', k: 1102  },
    ],
    stream: [
      { src: 'X',        s: 'neg', t: 'Copilot chat started hallucinating imports from node_modules' },
      { src: 'HN',       s: 'neg', t: '"Actions runners are slow again — anyone else?"' },
      { src: 'FORUM',    s: 'neg', t: 'Actions queue time for Linux runners 4x baseline' },
      { src: 'ZENDESK',  s: 'neg', t: '#9912 · enterprise OIDC login loops after SSO refresh' },
      { src: 'X',        s: 'pos', t: 'new Copilot code review actually caught a real bug today' },
      { src: 'REDDIT',   s: 'neg', t: 'r/github · "PR diff takes 30s to render on large monorepos"' },
      { src: 'SLACK',    s: 'neg', t: '#actions-infra · runner scale-out lag during NA business hours' },
      { src: 'ISSUES',   s: 'neg', t: 'github/actions-runner#4902 · timeout on cold-start' },
      { src: 'FORUM',    s: 'neg', t: 'secret scanning false-positive rate way up this month' },
      { src: 'HN',       s: 'neu', t: '"GitHub Copilot Enterprise pricing thread"' },
      { src: 'X',        s: 'neg', t: 'why does Actions bill me for cancelled workflows now' },
      { src: 'ZENDESK',  s: 'neg', t: '#9930 · Copilot chat leaks cross-repo context in workspace' },
      { src: 'REDDIT',   s: 'neg', t: 'r/devops · "Actions latency makes CI unusable on Mondays"' },
      { src: 'ISSUES',   s: 'neg', t: 'github/docs#2211 · auth docs outdated for Enterprise SSO' },
      { src: 'X',        s: 'neu', t: 'Dependabot finally supports pnpm workspaces, thank you' },
    ],
    clusters: [
      { title: 'Actions runner queue latency', size: 2120, score: 92.6, top: true },
      { title: 'Enterprise SSO / OIDC loops',  size: 1420, score: 85.3 },
      { title: 'Copilot cross-repo leakage',   size: 1110, score: 81.2 },
      { title: 'PR diff render perf on monorepos', size: 820, score: 72.0 },
      { title: 'Secret-scan false positives',  size: 610,  score: 60.4 },
      { title: 'Actions billing edge cases',   size: 430,  score: 48.9 },
      { title: 'Copilot hallucinated imports', size: 380,  score: 44.1 },
    ],
    top: {
      title: 'Restore Actions runner queue-time SLO',
      why: 'GitHub\'s loudest signal is Actions latency degrading NA business hours. HN, Reddit, forum, and internal Slack all point at runner scale-out lag — directly blocking customer CI.',
      rec: 'Fix runner queue time before any new Actions surface ships.',
      rice: { R: 94, I: 90, C: 93, E: 22 },
      score: 92.6,
      verdict: 'CI-critical — every minute of lag multiplies across customers.',
      accept: [
        'p95 Linux runner queue time < 30s during NA business hours',
        'Auto-scaler warms pool based on historical Monday load',
        'Customer-facing status page includes queue-time chart',
        'Cancelled-workflow billing behavior clarified in docs',
      ],
      evidence: [
        { q: 'Actions latency makes CI unusable on Mondays.', src: 'r/devops' },
        { q: 'Runner queue time for Linux is 4x baseline for us.', src: 'Community forum' },
        { q: '#actions-infra — scale-out lag during NA business hours.', src: 'Slack · internal' },
      ],
      jira: { id: 'ACT-1820', type: 'Epic', proj: 'Actions', pts: 34 },
      conf: { space: 'ACT', title: 'PRD · Runner queue-time SLO restoration' },
    },
    counts: { signals: 33532, pct: { pos: 24, neu: 30, neg: 46 }, epics: 7, runtimeSec: 40 },
  },
};
